//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPlink.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ItestWCF")]
    public interface ItestWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItestWCF/DoWork", ReplyAction="http://tempuri.org/ItestWCF/DoWorkResponse")]
        string DoWork(string A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItestWCF/DoWork", ReplyAction="http://tempuri.org/ItestWCF/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync(string A);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItestWCF/ExecuteHS", ReplyAction="http://tempuri.org/ItestWCF/ExecuteHSResponse")]
        string ExecuteHS(string IP);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ItestWCF/ExecuteHS", ReplyAction="http://tempuri.org/ItestWCF/ExecuteHSResponse")]
        System.Threading.Tasks.Task<string> ExecuteHSAsync(string IP);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ItestWCFChannel : TestPlink.ServiceReference1.ItestWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ItestWCFClient : System.ServiceModel.ClientBase<TestPlink.ServiceReference1.ItestWCF>, TestPlink.ServiceReference1.ItestWCF {
        
        public ItestWCFClient() {
        }
        
        public ItestWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ItestWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItestWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ItestWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork(string A) {
            return base.Channel.DoWork(A);
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync(string A) {
            return base.Channel.DoWorkAsync(A);
        }
        
        public string ExecuteHS(string IP) {
            return base.Channel.ExecuteHS(IP);
        }
        
        public System.Threading.Tasks.Task<string> ExecuteHSAsync(string IP) {
            return base.Channel.ExecuteHSAsync(IP);
        }
    }
}
