//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShellStrikeService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\putty\\plink.exe")]
        public string PlinkPath {
            get {
                return ((string)(this["PlinkPath"]));
            }
            set {
                this["PlinkPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int ThreadLimit {
            get {
                return ((int)(this["ThreadLimit"]));
            }
            set {
                this["ThreadLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:9900/ShellData")]
        public string ShellTCPBinding {
            get {
                return ((string)(this["ShellTCPBinding"]));
            }
            set {
                this["ShellTCPBinding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int FetchInterval {
            get {
                return ((int)(this["FetchInterval"]));
            }
            set {
                this["FetchInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15000")]
        public int CommandEndTimeout {
            get {
                return ((int)(this["CommandEndTimeout"]));
            }
            set {
                this["CommandEndTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoOutputLogs {
            get {
                return ((bool)(this["DoOutputLogs"]));
            }
            set {
                this["DoOutputLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoRawOutputLogs {
            get {
                return ((bool)(this["DoRawOutputLogs"]));
            }
            set {
                this["DoRawOutputLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoProcessLogs {
            get {
                return ((bool)(this["DoProcessLogs"]));
            }
            set {
                this["DoProcessLogs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int ThreadMaxTimeout {
            get {
                return ((int)(this["ThreadMaxTimeout"]));
            }
            set {
                this["ThreadMaxTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int OutputRetryAttemps {
            get {
                return ((int)(this["OutputRetryAttemps"]));
            }
            set {
                this["OutputRetryAttemps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ISB-SSO-DB1;Failover Partner=LHE-SSO-DB1;Initial Catalog=dBColdStrike" +
            ";User ID=ssoadmin;Password=XM_on-26tcoinspiron")]
        public string dBColdStrikeConnectionString {
            get {
                return ((string)(this["dBColdStrikeConnectionString"]));
            }
            set {
                this["dBColdStrikeConnectionString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int CommandWait {
            get {
                return ((int)(this["CommandWait"]));
            }
            set {
                this["CommandWait"] = value;
            }
        }
    }
}
